export const ROUTES = {
  main: '/',
  login: '/login',
  register: '/register',
  verifyEmail: '/verify-email',
  createPassword: '/create-password',
  overview: '/overview',
  microLessons: '/microlessons',
  addContent: '/addcontent',
  lessons: '/lessons',
  createLesson: '/microlessons/create',
  courses: '/courses',
  createCourse: '/createcourse',
  campaigns: '/campaigns',
  statements: '/statements',
  settings: '/settings',
  payout: '/payout',
  dynamic: {
    microLessons: (id = ':id') => `/microlessons/${id}`,
    microLessonsAddQuestion: (mId = ':mId') => `/microlessons/${mId}/questions`,
    microLessonsQuestion: (mId = ':mId', qId = ':qId') => `/microlessons/${mId}/questions/${qId}`,
    microLessonsContent: (id = ':id') => `/microlessons/${id}/content`,
    lessons: (id = ':id') => `/lessons/${id}`,
    lessonsQuestion: (id = ':id') => `/lessons/${id}/questions`,
    courses: (id = ':id') => `/courses/${id}`,
    coursesQuestion: (id = ':id') => `/courses/${id}/questions`,
  },
};
