export const CREATE_MICROLESSON_REQUEST = 'CREATE_MICROLESSON_REQUEST' as const;
export const CREATE_MICROLESSON_FAILURE = 'CREATE_MICROLESSON_FAILURE' as const;
export const SET_CONTENT_SUCCESS = 'SET_CONTENT_SUCCESS' as const;
export const SET_MICROLESSON = 'SET_MICROLESSON' as const;
export const GET_ALL_MICROLESSONS = 'GET_ALL_MICROLESSONS' as const;
export const GET_ALL_MICROLESSONS_FAILED = 'GET_ALL_MICROLESSONS_FAILED' as const;
export const UPDATE_TAGS_FOR_MICROLESSON = 'UPDATE_TAGS_FOR_MICROLESSON' as const;
export const PUT_QUESTION_FOR_MICROLESSON = 'PUT_QUESTION_FOR_MICROLESSON' as const;

export const REMOVE_MICROLESSON = 'REMOVE_MICROLESSON' as const;
export const CREATE_MICROLESSON = 'CREATE_MICROLESSON' as const;
export const UPDATE_MICROLESSON = 'UPDATE_MICROLESSON' as const;
export const CREATE_QUESTION = 'CREATE_QUESTION' as const;
export const UPDATE_QUESTION = 'UPDATE_QUESTION' as const;
export const REMOVE_QUESTION = 'REMOVE_QUESTION' as const;
export const CREATE_ANSWER = 'CREATE_ANSWER' as const;
export const UPDATE_ANSWER = 'UPDATE_ANSWER' as const;
export const REMOVE_ANSWER = 'REMOVE_ANSWER' as const;
